#it's my makefile
all:
	#gcc -I/home/user/Downloads/libxml2-2.7.8/include main.c -Wall -g -O0 -L/home/user/Downloads/libxml2-2.7.8 -lxml2 -o server1
	#gcc -g -o0 -Wall -o ./Debug/Client1  main.c -lxml2 -I/home/user/Downloads/libxml2-2.7.8/include
	gcc -g -o0 -Wall -o ./Client3  main.c -lxml2 -I/home/user/Downloads/libxml2-2.7.8/include
	
clean:
	rm ./Client3
	rm *.o